### ISSUE TITLE
GIT Clone steps in Instructions refer to old repository name

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AI-102-AIEngineer.ko-kr#1]
# Module: (all)
#### Step: 00

Description of issue

The GIT Clone steps in the lab steps refer to the old repository, and should be updated to point to this new repository:

팔레트를 열고(Shift+Ctrl+P 누르기) Git: Clone 명령을 실행하여 https://github.com/MicrosoftLearning/AI-102KO-Designing-and-Implementing-a-Microsoft-Azure-AI-Solution 리포지토리를 로컬 폴더(아무 폴더나 관계없음)에 복제합니다.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by Chenpeng21** [comment]
This issue can no longer be reproduced.
![image](https://user-images.githubusercontent.com/93902755/181457452-6398ed8c-0c0c-44d0-9817-82843135b7bd.png)
