### ISSUE TITLE
[01-get-started-cognitive-services.md] Outdated Python package 

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/AI-102-AIEngineer.ko-kr#2]
# Module: 01
#### Step: 02

Description of issue
It is using outdated Python package version 5.1.0, which will cause error when going through the labs. It needs to be updated to 5.3.0. The [English lab instruction](https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/Instructions/01-get-started-cognitive-services.md) is using 5.3.0 version. 

Current:
`pip install azure-ai-textanalytics==5.1.0`

To be:
`pip install azure-ai-textanalytics==5.3.0`

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Link to [File ](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPkZhbHNlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtLb3JlYW4gKEtvcmVhKTwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0VxdWFsOzUwMzAwLkluc3RydWN0aW9ucy4wMS1nZXQtc3RhcnRlZC1jb2duaXRpdmUtc2VydmljZXMubWQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)

**Comment by stonezy123** [comment]
Now, the locfile fixed.
![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer.ko-kr/assets/49666210/1a44c05f-dc6a-42e8-88b1-b62632fcf9c5)
