### ISSUE TITLE
[02-cognitive-services-security.md] Outdated Python package

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/AI-102-AIEngineer.ko-kr#3]
# Module: 02
#### Step: 2

Description of issue
Python text analytics package needs to be updated to 5.3.0 in order to complete the labs without errors. [English lab instruction](https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/Instructions/02-cognitive-services-security.md#use-the-service-principal-in-an-application) already reflects this change. 

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer.ko-kr/assets/46511987/4ea2abc5-dd15-44da-ae1d-452ea3896ed9)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Link to Locfile[https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPkZhbHNlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtLb3JlYW4gKEtvcmVhKTwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0VxdWFsOzUwMzAwLkluc3RydWN0aW9ucy4wMi1jb2duaXRpdmUtc2VydmljZXMtc2VjdXJpdHkubWQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d](url)

**Comment by chriscarty00** [comment]
Locfile will need to be re-handed off to take the update for all langs - assigning to WWL PM

**Comment by stonezy123** [comment]
Now, the locfile fixed.
![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer.ko-kr/assets/49666210/f9a82919-4179-4011-88a5-40fb6f0a7ffe)
