### ISSUE TITLE
[04-use-a-container.md] Need to update ACI configurations

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/AI-102-AIEngineer.ko-kr#4]
# Module: 04
#### Step: 01

Description of issue
Need to update ACI configuration parameters to sync with the English lab instructions.

Current:
4GB
예

To be:
12GB
아니오

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer.ko-kr/assets/46511987/a4c77fdc-d4cc-4e17-9166-3d0d49aeb0d6)

![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer.ko-kr/assets/46511987/23911b19-8611-4bb8-95a0-4f71582ca019)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Link to Locfile [https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPkZhbHNlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtLb3JlYW4gKEtvcmVhKTwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0VxdWFsOzUwMzAwLkluc3RydWN0aW9ucy4wNC11c2UtYS1jb250YWluZXIubWQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d](url)

**Comment by chriscarty00** [comment]
Locfile need to be rehanded off to take latest updates

**Comment by stonezy123** [comment]
Now, the loc file fixed.
![image](https://github.com/MicrosoftLearning/AI-102-AIEngineer.ko-kr/assets/49666210/7fc9b434-b920-4b62-b451-9054a7a49f87)
